# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-13 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monoseo', '0002_auto_20200613_1831'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'type')]),
        ),
    ]
