# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-13 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monoseo', '0003_auto_20200613_2140'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together=set([('key', 'domain'), ('sector', 'id_project')]),
        ),
    ]
