# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-13 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monoseo', '0004_auto_20200613_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='id_project',
            new_name='project',
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together=set([('key', 'domain'), ('sector', 'project')]),
        ),
    ]
