# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-13 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monoseo', '0005_auto_20200614_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='id_user',
            new_name='user',
        ),
    ]
