# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monoseo', '0012_auto_20200624_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monoseo.Project'),
        ),
    ]
