# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monoseo', '0013_report_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.FileField(upload_to='reports/'),
        ),
    ]
